### PR TITLE
Problems 5, 6, 7, 8 and Structural Changes

### PR DESCRIPTION
**Pull request by notu97**

### CODE REVIEW

**Comment by notu97** [comment]
Problem 6: Symmetric Tree

**Comment by notu97** [comment]
Problem 7 and Structural changes added.

**Comment by ThreeMangoTrees** [comment]
Let's keep it simple. Inside Directory SBiswas create a sub-directory Milestone1. Put the problems you are solving inside it. For e.g.
```
SBiswas/Milestone1/Problem1.cs
SBiswas/Milestone1/Problem2.cs
SBiswas/Milestone1/Problem3.cs
```
etc.

**Comment by ThreeMangoTrees** [comment]
From next time, keep the method format same as in Leetcode. For e.g. The method format for the problem - Sum of Left Leaves, in Leetcode is - 

```
int sumOfLeftLeaves(TreeNode* root) {
        
}
``` 

but the format you have provided is - 
```
  void sum_left_leaves(Node* root, int& sum)
    {
       

    }
```

Also, I have removed the problem 4 so there is a change in the problem number as well. From next time follow the same numbering. 

But Great work Shila!

**Pull request merged**
